"""
jira_client — Fetch Jira tickets. Mock/real per USE_MOCK.
Part of: QA Orchestrator
Phase: 1
Mock-safe: yes
"""
import json
import logging
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

USE_MOCK: bool = os.getenv("USE_MOCK", "true").lower() == "true"


def get_ticket(jira_id: str) -> dict:
    """Fetch a Jira ticket by id. Loads from mock_data/jira when USE_MOCK=true."""
    if USE_MOCK:
        path = Path(f"mock_data/jira/{jira_id}.json")
        logger.info("[jira_client] Loading mock ticket: %s", path)
        return json.loads(path.read_text())

    from atlassian import Jira

    client = Jira(
        url=os.getenv("JIRA_BASE_URL"),
        username=os.getenv("JIRA_EMAIL"),
        password=os.getenv("JIRA_API_TOKEN"),
    )
    logger.info("[jira_client] Fetching real ticket: %s", jira_id)
    return client.issue(jira_id)


def post_comment(jira_id: str, comment: str) -> None:
    """Post a comment on a Jira ticket. Logs instead of posting when USE_MOCK=true."""
    if USE_MOCK:
        logger.info("[jira] MOCK: would post comment to %s", jira_id)
        return

    from atlassian import Jira

    client = Jira(
        url=os.getenv("JIRA_BASE_URL"),
        username=os.getenv("JIRA_EMAIL"),
        password=os.getenv("JIRA_API_TOKEN"),
    )
    client.issue_add_comment(jira_id, comment)


def format_test_cases_as_text(
    test_cases: list[dict],
    jira_id: str,
    jira_summary: str,
) -> str:
    """
    Format autonomous QA test cases as a professional markdown table.
    Column order matches copilot-instructions.md Section 6.2 exactly.
    Renders as a table in Jira when saved as a .md file.

    Args:
        test_cases:   List of test case dicts from test_case_agent
        jira_id:      Jira ticket ID eg. PROJ-123
        jira_summary: Jira ticket summary line

    Returns:
        Formatted markdown string
    """
    from datetime import datetime

    lines = [
        f"# Test Cases — {jira_id}",
        f"**Ticket:** {jira_summary}",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**Total:** {len(test_cases)} test cases",
        "**Generated by:** QA Orchestrator — Fully Autonomous Agentic System",
        "**Human approval gate:** None — fully autonomous execution",
        "",
    ]

    smoke = sum(1 for c in test_cases if c.get("type") == "Smoke")
    functional = sum(1 for c in test_cases if c.get("type") == "Functional")
    regression = sum(1 for c in test_cases if c.get("type") == "Regression")
    positive = sum(1 for c in test_cases if c.get("scenario_nature") == "Positive")
    negative = sum(1 for c in test_cases if c.get("scenario_nature") == "Negative")
    passed = sum(1 for c in test_cases if "Passed" in c.get("automation_status", ""))
    failed = sum(1 for c in test_cases if "Failed" in c.get("automation_status", ""))
    healed = sum(1 for c in test_cases if "Healed" in c.get("automation_status", ""))

    lines += [
        "## Execution Summary",
        "",
        "| Category | Count |",
        "|----------|-------|",
        f"| Smoke tests | {smoke} |",
        f"| Functional tests | {functional} |",
        f"| Regression tests | {regression} |",
        f"| Positive scenarios | {positive} |",
        f"| Negative scenarios | {negative} |",
        f"| Executed - Passed | {passed} |",
        f"| Executed - Failed | {failed} |",
        f"| Executed - Healed | {healed} |",
        "",
        "---",
        "",
        "## Test Cases",
        "",
        "| Jira Id | Test Case ID | Module | Sub-Module | Priority | Type | "
        "Test Case Description | Preconditions | Test Steps | Expected Results | "
        "Postconditions | Tags | Automation Status | Remarks | "
        "Scenario Nature | Negative Category |",
        "|---------|-------------|--------|-----------|----------|------|"
        "---------------------|--------------|------------|-----------------|"
        "---------------|------|------------------|---------|"
        "----------------|-------------------|",
    ]

    def fmt_list(val: object) -> str:
        if isinstance(val, list):
            return " ↵ ".join(str(v) for v in val)
        return str(val) if val else ""

    for tc in test_cases:
        row = (
            f"| {tc.get('jira_id', jira_id)} "
            f"| {tc.get('test_case_id', '')} "
            f"| {tc.get('module', '')} "
            f"| {tc.get('sub_module', '')} "
            f"| {tc.get('priority', '')} "
            f"| {tc.get('type', '')} "
            f"| {tc.get('test_case_description', '')} "
            f"| {fmt_list(tc.get('preconditions', ''))} "
            f"| {fmt_list(tc.get('test_steps', ''))} "
            f"| {fmt_list(tc.get('expected_results', ''))} "
            f"| {tc.get('postconditions', '')} "
            f"| {tc.get('tags', '')} "
            f"| {tc.get('automation_status', 'Auto-Generated')} "
            f"| {tc.get('remarks', '')} "
            f"| {tc.get('scenario_nature', '')} "
            f"| {tc.get('negative_category', 'NA')} |"
        )
        lines.append(row)

    lines += ["", "---", "", "## Detailed Test Cases", ""]

    for tc in test_cases:
        lines += [
            f"### {tc.get('test_case_id', '')} — {tc.get('test_case_description', '')}",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| **Jira Id** | {tc.get('jira_id', jira_id)} |",
            f"| **Module** | {tc.get('module', '')} |",
            f"| **Sub-Module** | {tc.get('sub_module', '')} |",
            f"| **Priority** | {tc.get('priority', '')} |",
            f"| **Type** | {tc.get('type', '')} |",
            f"| **Tags** | {tc.get('tags', '')} |",
            f"| **Automation Status** | {tc.get('automation_status', 'Auto-Generated')} |",
            f"| **Scenario Nature** | {tc.get('scenario_nature', '')} |",
            f"| **Negative Category** | {tc.get('negative_category', 'NA')} |",
            "",
            "**Preconditions:**",
        ]
        for item in (tc.get("preconditions") or []):
            lines.append(f"- {item}")

        lines += ["", "**Test Steps:**"]
        for step in (tc.get("test_steps") or []):
            lines.append(f"{step}")

        lines += ["", "**Expected Results:**"]
        for res in (tc.get("expected_results") or []):
            lines.append(f"{res}")

        lines += [
            "",
            f"**Postconditions:** {tc.get('postconditions', '')}",
            "",
            f"**Remarks:** {tc.get('remarks', '')}",
            "",
            "---",
            "",
        ]

    return "\n".join(lines)


def attach_file_to_ticket(
    jira_id: str,
    file_path: str,
    file_name: str,
) -> bool:
    """
    Attach a local file to a Jira ticket.
    Mock: saves copy to outputs/attachments/ and prints to console.
    Real: uploads via Jira REST API attachment endpoint.

    Args:
        jira_id:   Jira ticket ID eg. PROJ-123
        file_path: Absolute or relative path to the local file
        file_name: Display name for the attachment in Jira

    Returns:
        True if attachment succeeded, False if failed
    """
    if USE_MOCK:
        attach_dir = Path("outputs/attachments")
        attach_dir.mkdir(parents=True, exist_ok=True)
        dest = attach_dir / f"{jira_id}_{file_name}"
        dest.write_text(Path(file_path).read_text())
        logger.info("[jira_client] MOCK attachment saved: %s", dest)
        print("\n=== MOCK JIRA ATTACHMENT ===")
        print(f"Ticket:    {jira_id}")
        print(f"File:      {file_name}")
        print(f"Saved at:  {dest}")
        print("=" * 30)
        return True

    try:
        from atlassian import Jira
        client = Jira(
            url=os.getenv("JIRA_BASE_URL"),
            username=os.getenv("JIRA_EMAIL"),
            password=os.getenv("JIRA_API_TOKEN"),
        )
        with open(file_path, "rb") as f:
            client.add_attachment(jira_id, f, filename=file_name)
        logger.info("[jira_client] Attached %s to %s", file_name, jira_id)
        return True
    except Exception as e:
        logger.error("[jira_client] Attachment failed for %s: %s",
                     jira_id, str(e))
        return False
