"""
jira_client — Fetch Jira tickets. Mock/real per USE_MOCK.
Part of: QA Orchestrator
Phase: 1
Mock-safe: yes
"""
import json
import logging
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

USE_MOCK: bool = os.getenv("USE_MOCK", "true").lower() == "true"


def get_ticket(jira_id: str) -> dict:
    """Fetch a Jira ticket by id. Loads from mock_data/jira when USE_MOCK=true."""
    if USE_MOCK:
        path = Path(f"mock_data/jira/{jira_id}.json")
        logger.info("[jira_client] Loading mock ticket: %s", path)
        return json.loads(path.read_text())

    from atlassian import Jira

    client = Jira(
        url=os.getenv("JIRA_BASE_URL"),
        username=os.getenv("JIRA_EMAIL"),
        password=os.getenv("JIRA_API_TOKEN"),
    )
    logger.info("[jira_client] Fetching real ticket: %s", jira_id)
    return client.issue(jira_id)


def post_comment(jira_id: str, comment: str) -> None:
    """Post a comment on a Jira ticket. Logs instead of posting when USE_MOCK=true."""
    if USE_MOCK:
        logger.info("[jira] MOCK: would post comment to %s", jira_id)
        return

    from atlassian import Jira

    client = Jira(
        url=os.getenv("JIRA_BASE_URL"),
        username=os.getenv("JIRA_EMAIL"),
        password=os.getenv("JIRA_API_TOKEN"),
    )
    client.issue_add_comment(jira_id, comment)


def format_test_cases_as_text(
    test_cases: list[dict],
    jira_id: str,
    jira_summary: str,
) -> str:
    """
    Format generated test cases as a readable plain text document
    for attaching to a Jira ticket.

    Args:
        test_cases:   List of test case dicts from test_case_agent
        jira_id:      Jira ticket ID eg. PROJ-123
        jira_summary: Jira ticket summary line

    Returns:
        Formatted plain text string
    """
    from datetime import datetime

    lines = [
        "=" * 60,
        f"TEST CASES — {jira_id}",
        f"Ticket: {jira_summary}",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"Total: {len(test_cases)} test cases",
        "=" * 60,
        "",
    ]

    priority_labels = {"P1": "CRITICAL", "P2": "HIGH", "P3": "MEDIUM"}

    for priority in ["P1", "P2", "P3"]:
        priority_cases = [
            tc for tc in test_cases
            if tc.get("priority") == priority
        ]
        if not priority_cases:
            continue

        lines.append(
            f"── {priority} — {priority_labels.get(priority, priority)} ──"
        )
        lines.append("")

        for tc in priority_cases:
            lines.append(f"Test ID:  {tc.get('id', 'N/A')}")
            lines.append(f"Flow:     {tc.get('flow', 'N/A')}")
            lines.append(f"Type:     {tc.get('type', 'ui').upper()}")
            lines.append(f"Priority: {tc.get('priority', 'N/A')}")
            lines.append("")
            lines.append(f"  GIVEN:  {tc.get('given', '')}")
            lines.append(f"  WHEN:   {tc.get('when', '')}")
            lines.append(f"  THEN:   {tc.get('then', '')}")
            lines.append("")
            lines.append("-" * 50)
            lines.append("")

    lines.append("=" * 60)
    lines.append(
        "Generated by QA Orchestrator — Agentic QA Automation System"
    )
    lines.append("NOTE: Test execution results will be posted as a")
    lines.append("Jira comment once all tests have completed.")
    lines.append("=" * 60)

    return "\n".join(lines)


def attach_file_to_ticket(
    jira_id: str,
    file_path: str,
    file_name: str,
) -> bool:
    """
    Attach a local file to a Jira ticket.
    Mock: saves copy to outputs/attachments/ and prints to console.
    Real: uploads via Jira REST API attachment endpoint.

    Args:
        jira_id:   Jira ticket ID eg. PROJ-123
        file_path: Absolute or relative path to the local file
        file_name: Display name for the attachment in Jira

    Returns:
        True if attachment succeeded, False if failed
    """
    if USE_MOCK:
        attach_dir = Path("outputs/attachments")
        attach_dir.mkdir(parents=True, exist_ok=True)
        dest = attach_dir / f"{jira_id}_{file_name}"
        dest.write_text(Path(file_path).read_text())
        logger.info("[jira_client] MOCK attachment saved: %s", dest)
        print("\n=== MOCK JIRA ATTACHMENT ===")
        print(f"Ticket:    {jira_id}")
        print(f"File:      {file_name}")
        print(f"Saved at:  {dest}")
        print("=" * 30)
        return True

    try:
        from atlassian import Jira
        client = Jira(
            url=os.getenv("JIRA_BASE_URL"),
            username=os.getenv("JIRA_EMAIL"),
            password=os.getenv("JIRA_API_TOKEN"),
        )
        with open(file_path, "rb") as f:
            client.add_attachment(jira_id, f, filename=file_name)
        logger.info("[jira_client] Attached %s to %s", file_name, jira_id)
        return True
    except Exception as e:
        logger.error("[jira_client] Attachment failed for %s: %s",
                     jira_id, str(e))
        return False
